package Generador;


import com.itextpdf.text.DocumentException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import jbarcodebean.JBarcodeBean;
import net.sourceforge.jbarcodebean.model.Codabar;
import net.sourceforge.jbarcodebean.model.Code11;
import net.sourceforge.jbarcodebean.model.Code128;
import net.sourceforge.jbarcodebean.model.Code39;
import net.sourceforge.jbarcodebean.model.Code39_2to1;
import net.sourceforge.jbarcodebean.model.Code93;
import net.sourceforge.jbarcodebean.model.Code93Extended;
import net.sourceforge.jbarcodebean.model.Ean13;
import net.sourceforge.jbarcodebean.model.Ean8;
import net.sourceforge.jbarcodebean.model.Interleaved25;
import net.sourceforge.jbarcodebean.model.MSI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yonathan Román
 */
public class Generador extends javax.swing.JFrame {

    JBarcodeBean barcode = new JBarcodeBean();
    public static BufferedImage imagen = null;
    int lar,anc;
    
    /**
     * Creates new form Generador
     */
    public Generador() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtlargo.setEditable(false);
        txtancho.setEditable(false);
        setIconImage(new ImageIcon(getClass().getResource("/img/logo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codeimg = new javax.swing.JLabel();
        Generarbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        Guardarbtn = new javax.swing.JButton();
        Limpiarbtn = new javax.swing.JButton();
        PDFbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        check = new javax.swing.JCheckBox();
        txtlargo = new javax.swing.JTextField();
        txtancho = new javax.swing.JTextField();
        acerca = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        generatorCode = new javax.swing.JComboBox<>();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generador de codigos de barras");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Generador de codigos de barras");

        codeimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codeimg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Generarbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Generarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/codebarimg.png"))); // NOI18N
        Generarbtn.setText("Generar");
        Generarbtn.setFocusable(false);
        Generarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarbtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Código: ");

        txtCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        Guardarbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Guardarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        Guardarbtn.setText("Guardar");
        Guardarbtn.setFocusable(false);
        Guardarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarbtnActionPerformed(evt);
            }
        });

        Limpiarbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Limpiarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        Limpiarbtn.setText("Limpiar");
        Limpiarbtn.setFocusable(false);
        Limpiarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarbtnActionPerformed(evt);
            }
        });

        PDFbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PDFbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdf.png"))); // NOI18N
        PDFbtn.setText("PDF");
        PDFbtn.setFocusable(false);
        PDFbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDFbtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Largo:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Ancho:");

        check.setBackground(new java.awt.Color(255, 255, 255));
        check.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        check.setText("Tamaño de imagen");
        check.setFocusable(false);
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        txtlargo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtlargo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtlargo.setText("50");
        txtlargo.setToolTipText("Debe de ser mayor a 100 pixeles");
        txtlargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtlargoKeyTyped(evt);
            }
        });

        txtancho.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtancho.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtancho.setText("25");
        txtancho.setToolTipText("Debe de ser mayor a 70 pixeles");
        txtancho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtanchoKeyTyped(evt);
            }
        });

        acerca.setText("Acerca");
        acerca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acerca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acercaMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Generador:");

        generatorCode.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        generatorCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ean8", "Ean13", "Code39", "Code128", "Interleaved25", "CodaBar", "Code11", "Code 39 Extended", "Code 93 Extended", "Code93", "MSI" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codeimg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generatorCode, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Generarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Guardarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Limpiarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PDFbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(acerca))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(check)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtlargo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtancho, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(codeimg, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(generatorCode))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlargo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtancho, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Generarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Guardarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Limpiarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PDFbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acerca)
                    .addComponent(jLabel6)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenerarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarbtnActionPerformed
        if (this.txtCodigo.getText().length() < 1) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un valor.", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            System.out.println(generatorCode.getSelectedIndex());
            generaCodigo(txtCodigo.getText(),generatorCode.getSelectedIndex());
        }
    }//GEN-LAST:event_GenerarbtnActionPerformed

    private void LimpiarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarbtnActionPerformed
        txtCodigo.setText("");
        codeimg.setIcon(null);
        imagen = null;
        check.setSelected(false);
        txtlargo.setEditable(false);
        txtancho.setEditable(false);
        txtlargo.setText("50");
        txtancho.setText("25");
    }//GEN-LAST:event_LimpiarbtnActionPerformed

    private void GuardarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarbtnActionPerformed
        if (imagen == null) {
            JOptionPane.showMessageDialog(this, "Debe generar un código.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if(check.isSelected()){
                generaCodigo(txtCodigo.getText(),generatorCode.getSelectedIndex());
            }
            if (new Guardar().guardarImagen()) {
                JOptionPane.showMessageDialog(this, "Imagen guardada con éxito.", "Información", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_GuardarbtnActionPerformed

    private void PDFbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDFbtnActionPerformed
        if(imagen == null){
            JOptionPane.showMessageDialog(this, "Debe generar un código.", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            if(check.isSelected()){
                check.setSelected(false);
                txtlargo.setEditable(false);
            txtancho.setEditable(false);
//            txtlargo.setText("110");
//            txtancho.setText("70");
                JOptionPane.showMessageDialog(this, "El tamaño de la imagen cambio a 110x70 para guardar como PDF", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                generaCodigo(txtCodigo.getText(),generatorCode.getSelectedIndex());
            }
            
        try {
            new PDFcrear().guard();
        } catch (IOException ex) {
            Logger.getLogger(Generador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(Generador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
    }//GEN-LAST:event_PDFbtnActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        if(check.isSelected()){
            txtlargo.setEditable(true);
            txtancho.setEditable(true);
        }else{
            txtlargo.setEditable(false);
            txtancho.setEditable(false);
            txtlargo.setText("50");
            txtancho.setText("25");
            if(imagen==null){
                
            }else{
            generaCodigo(txtCodigo.getText(),generatorCode.getSelectedIndex());
        }
        }
    }//GEN-LAST:event_checkActionPerformed

    private void txtlargoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlargoKeyTyped
        int caracteres=3;
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();  //Limita solo la escritura de digitos en el jtextfield
        if(txtlargo.getText().length()>=caracteres){
           evt.consume();
        }
        
    }//GEN-LAST:event_txtlargoKeyTyped

    private void txtanchoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtanchoKeyTyped
        int caracteres=3;
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();  //Limita solo la escritura de digitos en el jtextfield
        if(txtancho.getText().length()>=caracteres){
           evt.consume();
        }
    }//GEN-LAST:event_txtanchoKeyTyped

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
//        int caracteres=13;
//        char c = evt.getKeyChar();
//        if(c<'0' || c>'9') evt.consume();  //Limita solo la escritura de digitos en el jtextfield
//        if(txtCodigo.getText().length()>=caracteres){
//           evt.consume();
//        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void acercaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acercaMouseClicked
        JOptionPane.showMessageDialog(this, "SOFTWARE DESARROLLADO POR:\n  Yonathan Román\n  YonathanR ©", "Informacion", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_acercaMouseClicked

    private void generaCodigo(String codigo , int CodeType) {
        int LargoVar,AnchoVAar;
        lar = Integer.parseInt(txtlargo.getText());
        anc = Integer.parseInt(txtancho.getText());
        LargoVar=(int) (lar*3.7);
        AnchoVAar=(int) (anc*3.7);
//        LargoVar=(int) (lar*0.02636);
//        AnchoVAar=(int) (anc*3.7);
//        System.out.println("Pixeles: Largo:"+A+" Ancho: "+B);
        // nuestro tipo de codigo de barra
        switch (CodeType) {
            case 0:
                barcode.setCodeType(new Ean8());
                break;
            case 1:
                barcode.setCodeType(new Ean13());
                break;
            case 2:
                barcode.setCodeType(new Code39());
                break;
            case 3:
                barcode.setCodeType(new Code128());
                break;
            case 4:
                barcode.setCodeType(new Interleaved25());
                break;
            case 5:
                barcode.setCodeType(new Codabar());
                break;
            case 6:
                barcode.setCodeType(new Code11());
                break;
            case 7:
                barcode.setCodeType(new Code39_2to1());
                break;
            case 8:
                barcode.setCodeType(new Code93Extended());
                break;
            case 9:
                barcode.setCodeType(new Code93());
                break;
            case 10:
                barcode.setCodeType(new MSI());
                break;
        }

        // nuestro valor a codificar y algunas configuraciones mas
        barcode.setCode(codigo);
        barcode.setCheckDigit(true);
        imagen = barcode.draw(new BufferedImage(LargoVar, AnchoVAar, BufferedImage.TYPE_INT_RGB));
        ImageIcon barras = new ImageIcon(imagen);
          Icon icono = new ImageIcon(barras.getImage().getScaledInstance(codeimg.getWidth(),codeimg.getHeight(),Image.SCALE_DEFAULT));
          codeimg.setIcon(icono);
          this.repaint();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Generador.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(Generador.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(Generador.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Generador.class.getName()).log(Level.SEVERE, null, ex);
                }
                new Generador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Generarbtn;
    private javax.swing.JButton Guardarbtn;
    private javax.swing.JButton Limpiarbtn;
    private javax.swing.JButton PDFbtn;
    private javax.swing.JLabel acerca;
    private javax.swing.JCheckBox check;
    public javax.swing.JLabel codeimg;
    private javax.swing.JComboBox<String> generatorCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtancho;
    private javax.swing.JTextField txtlargo;
    // End of variables declaration//GEN-END:variables
}
